/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ['"DM Sans"', "sans-serif"],
      },
      colors: {
        border: "#E8E4DD",
        input: "#E8E4DD",
        ring: "#8C0B42",
        background: "#F7F5F0",
        foreground: "#0F0710",
        primary: { DEFAULT: "#8C0B42", foreground: "#FFFFFF" },
        secondary: { DEFAULT: "#F7F5F0", foreground: "#0F0710" },
        destructive: { DEFAULT: "#B3261E", foreground: "#FFFFFF" },
        muted: { DEFAULT: "#F7F5F0", foreground: "#5C544D" },
        accent: { DEFAULT: "#F7F5F0", foreground: "#0F0710" },
        card: { DEFAULT: "#FFFFFF", foreground: "#0F0710" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#0F0710" },
        "primary-dark": "#6B0833",
        "primary-light": "#FDF2F6",
        "primary-200": "#F4D5E0",
        bg: "#F7F5F0",
        ink: "#0F0710",
        dark: "#5C544D",
        mid: "#9C9690",
        success: "#2E7D4F",
        "success-light": "#E8F3EC",
        warning: "#C77A0B",
        "warning-light": "#FBF1DC",
        danger: "#B3261E",
        "danger-light": "#FBE9E7",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "14px",
        "2xl": "18px",
      },
      boxShadow: {
        card: "0 2px 6px rgba(0,0,0,0.04)",
        floaty: "0 4px 16px rgba(0,0,0,0.05)",
        modal: "0 30px 60px -20px rgba(0,0,0,0.30)",
        primary: "0 8px 16px rgba(140,11,66,0.35)",
      },
    },
  },
  plugins: [],
};
